### ISSUE TITLE
Multi protocol support for mc-router

### ISSUE THREAD

**Issue by memelord31337** [itzg/mc-router#337] opened 2024-10-27 23:53 UTC
Would like to use mc-router to handle the routing of bedrock and java clients to the same or different destination IPs/ports.

Tried to use -api-binding 0.0.0.0:19132 and supporting JSON config and did not work as desired.

Thanks

willing to provide test environment

**Comment by itzg** [comment] 2024-10-28 01:14
Sorry, not supported and I have no idea if it's even possible to add. 

Duplicate of #15

**Closed** 2024-10-28 01:14 UTC
